import 'dart:io';
import 'package:intl/intl.dart';
import 'package:path_provider/path_provider.dart';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:share_plus/share_plus.dart';
import 'package:csv/csv.dart';
import '../../shared/models/trip.dart';

class ReportService {
  static Future<void> generateCsv(List<Trip> trips, int year) async {
    List<List<dynamic>> rows = [];

    // Headers
    rows.add([
      "Date",
      "Departure",
      "Destination",
      "Purpose",
      "Km",
      "Category",
      "Deduction (CAD)",
      "Notes"
    ]);

    for (var trip in trips) {
      rows.add([
        DateFormat('yyyy-MM-dd').format(trip.date),
        trip.startAddress,
        trip.endAddress,
        trip.purpose,
        trip.distanceKm.toStringAsFixed(2),
        trip.category,
        trip.deductionCad.toStringAsFixed(2),
        trip.notes ?? ""
      ]);
    }

    // Fix: Use ListToCsvConverter class from the csv package
    String csvData = const ListToCsvConverter().convert(rows);
    final directory = await getTemporaryDirectory();
    final file = File('${directory.path}/Aurora_Report_$year.csv');
    await file.writeAsString(csvData);

    // Fix: Use the updated SharePlus API
    await SharePlus.instance.share(ShareParams(
      files: [XFile(file.path)],
      subject: 'My CRA Mileage Report for $year',
    ));
  }

  static Future<void> generatePdf(List<Trip> trips, int year, Map<String, double> stats) async {
    final pdf = pw.Document();

    pdf.addPage(
      pw.MultiPage(
        pageFormat: PdfPageFormat.a4,
        margin: const pw.EdgeInsets.all(32),
        build: (context) => [
          pw.Header(
            level: 0,
            child: pw.Row(
              mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
              children: [
                pw.Text('CRA Mileage Logbook $year', style: pw.TextStyle(fontSize: 24, fontWeight: pw.FontWeight.bold)),
                pw.Text('Generated by Aurora', style: const pw.TextStyle(fontSize: 10)),
              ],
            ),
          ),
          pw.SizedBox(height: 20),
          _buildSummarySection(stats),
          pw.SizedBox(height: 20),
          pw.TableHelper.fromTextArray(
            headerStyle: pw.TextStyle(fontWeight: pw.FontWeight.bold),
            headers: ['Date', 'From/To', 'Purpose', 'Km', 'Cat', 'Ded.'],
            data: trips.map((t) => [
              DateFormat('MM-dd').format(t.date),
              '${t.startAddress} to ${t.endAddress}',
              t.purpose,
              t.distanceKm.toStringAsFixed(1),
              t.category.substring(0, 1),
              '\$${t.deductionCad.toStringAsFixed(2)}'
            ]).toList(),
          ),
          pw.SizedBox(height: 40),
          pw.Divider(),
          pw.Center(
            child: pw.Text(
              'Keep this log with your tax records. CRA may request it for up to 6 years.',
              style: pw.TextStyle(fontSize: 10, fontStyle: pw.FontStyle.italic),
            ),
          ),
        ],
      ),
    );

    final directory = await getTemporaryDirectory();
    final file = File('${directory.path}/Aurora_Logbook_$year.pdf');
    await file.writeAsBytes(await pdf.save());

    // Fix: Use the updated SharePlus API
    await SharePlus.instance.share(ShareParams(
      files: [XFile(file.path)],
      subject: 'My CRA Logbook for $year',
    ));
  }

  static pw.Widget _buildSummarySection(Map<String, double> stats) {
    return pw.Container(
      padding: const pw.EdgeInsets.all(10),
      decoration: pw.BoxDecoration(
        border: pw.Border.all(color: PdfColors.grey300),
        borderRadius: const pw.BorderRadius.all(pw.Radius.circular(8)),
      ),
      child: pw.Column(
        crossAxisAlignment: pw.CrossAxisAlignment.start,
        children: [
          pw.Text('Summary', style: pw.TextStyle(fontWeight: pw.FontWeight.bold, fontSize: 16)),
          pw.Divider(),
          _summaryRow('Total Business Deduction', '\$${stats['totalDeduction']?.toStringAsFixed(2)}'),
          _summaryRow('Business km (Tier 1)', '${stats['kmUnder5k']?.toStringAsFixed(1)} km'),
          _summaryRow('Business km (Tier 2)', '${stats['kmOver5k']?.toStringAsFixed(1)} km'),
          _summaryRow('Medical/Moving', '\$${stats['medical']?.toStringAsFixed(2)}'),
          _summaryRow('Charity/Volunteer', '\$${stats['charity']?.toStringAsFixed(2)}'),
        ],
      ),
    );
  }

  static pw.Widget _summaryRow(String label, String value) {
    return pw.Padding(
      padding: const pw.EdgeInsets.symmetric(vertical: 2),
      child: pw.Row(
        mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
        children: [
          pw.Text(label),
          pw.Text(value, style: pw.TextStyle(fontWeight: pw.FontWeight.bold)),
        ],
      ),
    );
  }
}
